import type { AuthUser } from '@/types/auth.types';
import type { Student } from '@/types/student.types';
import type { FeeRecord, Receipt } from '@/types/fee.types';
import type { Staff, PayrollRecord } from '@/types/staff.types';
import type { School } from '@/types/school.types';
import type { Exam, ExamResult, ResultDeliveryRecord } from '@/types/exam.types';

export const SCHOOL_ID = 'sch-green-valley';

export const MOCK_USERS: Record<string, { password: string; user: AuthUser; token: string }> = {
  'saas@schoolops.io': {
    password: 'admin123',
    token: 'mock-saas-token',
    user: {
      id: 'u-saas',
      name: 'Zain',
      email: 'saas@schoolops.io',
      role: 'saas_admin',
      schoolId: null,
      schoolName: null,
      schoolLogo: null,
    },
  },
  'owner@greenvalley.edu.pk': {
    password: 'admin123',
    token: 'mock-owner-token',
    user: {
      id: 'u-owner',
      name: 'Imran Qureshi',
      email: 'owner@greenvalley.edu.pk',
      role: 'owner',
      schoolId: SCHOOL_ID,
      schoolName: 'Green Valley Academy',
      schoolLogo: null,
    },
  },
  'admin@greenvalley.edu.pk': {
    password: 'admin123',
    token: 'mock-admin-token',
    user: {
      id: 'u-admin',
      name: 'Sana Khan',
      email: 'admin@greenvalley.edu.pk',
      role: 'admin',
      schoolId: SCHOOL_ID,
      schoolName: 'Green Valley Academy',
      schoolLogo: null,
    },
  },
  'teacher@greenvalley.edu.pk': {
    password: 'admin123',
    token: 'mock-teacher-token',
    user: {
      id: 'u-teacher',
      name: 'Usman Malik',
      email: 'teacher@greenvalley.edu.pk',
      role: 'teacher',
      schoolId: SCHOOL_ID,
      schoolName: 'Green Valley Academy',
      schoolLogo: null,
    },
  },
};

export const MOCK_STUDENTS: Student[] = [
  {
    id: 'st-1',
    studentId: 'ADM-2026-0001',
    name: 'Ahmed Ali',
    fatherName: 'Khalid Ali',
    dateOfBirth: '2012-05-14',
    gender: 'male',
    phone: '0300-1234567',
    address: 'House 42, Gulberg III, Lahore',
    photo: null,
    classId: 'c8',
    className: 'Class 8',
    sectionId: 's8a',
    sectionName: 'A',
    sessionId: 'sess-2627',
    admissionDate: '2026-04-05',
    monthlyFee: 8000,
    discount: 500,
    status: 'active',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'st-2',
    studentId: 'ADM-2026-0002',
    name: 'Fatima Khan',
    fatherName: 'Tariq Khan',
    dateOfBirth: '2013-08-22',
    gender: 'female',
    phone: '0321-9876543',
    address: 'Street 7, Model Town, Lahore',
    photo: null,
    classId: 'c7',
    className: 'Class 7',
    sectionId: 's7a',
    sectionName: 'A',
    sessionId: 'sess-2627',
    admissionDate: '2026-04-08',
    monthlyFee: 6500,
    discount: 0,
    status: 'active',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'st-3',
    studentId: 'ADM-2026-0003',
    name: 'Hassan Raza',
    fatherName: 'Javed Raza',
    dateOfBirth: '2011-01-30',
    gender: 'male',
    phone: '0333-4567890',
    address: 'Block C, DHA Phase 5, Lahore',
    photo: null,
    classId: 'c9',
    className: 'Class 9',
    sectionId: 's9a',
    sectionName: 'A',
    sessionId: 'sess-2627',
    admissionDate: '2026-04-02',
    monthlyFee: 9000,
    discount: 1000,
    status: 'active',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'st-4',
    studentId: 'ADM-2026-0004',
    name: 'Ayesha Malik',
    fatherName: 'Shahid Malik',
    dateOfBirth: '2014-11-05',
    gender: 'female',
    phone: '0345-1122334',
    address: 'Johar Town, Lahore',
    photo: null,
    classId: 'c6',
    className: 'Class 6',
    sectionId: 's6b',
    sectionName: 'B',
    sessionId: 'sess-2627',
    admissionDate: '2026-04-10',
    monthlyFee: 5000,
    discount: 0,
    status: 'active',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'st-5',
    studentId: 'ADM-2026-0005',
    name: 'Bilal Ahmed',
    fatherName: 'Naveed Ahmed',
    dateOfBirth: '2010-03-18',
    gender: 'male',
    phone: '0301-5566778',
    address: 'Cantt Area, Lahore',
    photo: null,
    classId: 'c10',
    className: 'Class 10',
    sectionId: 's10a',
    sectionName: 'A',
    sessionId: 'sess-2627',
    admissionDate: '2026-03-28',
    monthlyFee: 12000,
    discount: 1500,
    status: 'active',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'st-6',
    studentId: 'ADM-2026-0006',
    name: 'Zainab Hussain',
    fatherName: 'Ali Hussain',
    dateOfBirth: '2012-07-09',
    gender: 'female',
    phone: '0312-9988776',
    address: 'Garden Town, Lahore',
    photo: null,
    classId: 'c8',
    className: 'Class 8',
    sectionId: 's8b',
    sectionName: 'B',
    sessionId: 'sess-2627',
    admissionDate: '2026-04-12',
    monthlyFee: 7500,
    discount: 0,
    status: 'active',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'st-7',
    studentId: 'ADM-2026-0007',
    name: 'Usman Sheikh',
    fatherName: 'Rashid Sheikh',
    dateOfBirth: '2013-09-25',
    gender: 'male',
    phone: '0308-4433221',
    address: 'Faisal Town, Lahore',
    photo: null,
    classId: 'c7',
    className: 'Class 7',
    sectionId: 's7b',
    sectionName: 'B',
    sessionId: 'sess-2627',
    admissionDate: '2026-04-15',
    monthlyFee: 6000,
    discount: 500,
    status: 'inactive',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'st-8',
    studentId: 'ADM-2026-0008',
    name: 'Maryam Siddiqui',
    fatherName: 'Omar Siddiqui',
    dateOfBirth: '2011-12-01',
    gender: 'female',
    phone: '0334-6677889',
    address: 'Bahria Town, Lahore',
    photo: null,
    classId: 'c9',
    className: 'Class 9',
    sectionId: 's9b',
    sectionName: 'B',
    sessionId: 'sess-2627',
    admissionDate: '2026-04-01',
    monthlyFee: 8500,
    discount: 0,
    status: 'active',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'st-9',
    studentId: 'ADM-2025-0142',
    name: 'Hamza Iqbal',
    fatherName: 'Iqbal Hussain',
    dateOfBirth: '2009-06-20',
    gender: 'male',
    phone: '0302-7788990',
    address: 'Wapda Town, Lahore',
    photo: null,
    classId: 'c10',
    className: 'Class 10',
    sectionId: 's10b',
    sectionName: 'B',
    sessionId: 'sess-2627',
    admissionDate: '2025-04-03',
    monthlyFee: 10000,
    discount: 0,
    status: 'graduated',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'st-10',
    studentId: 'ADM-2026-0009',
    name: 'Sanaullah Butt',
    fatherName: 'Asif Butt',
    dateOfBirth: '2014-02-14',
    gender: 'male',
    phone: '0315-2233445',
    address: 'Allama Iqbal Town, Lahore',
    photo: null,
    classId: 'c6',
    className: 'Class 6',
    sectionId: 's6a',
    sectionName: 'A',
    sessionId: 'sess-2627',
    admissionDate: '2026-05-01',
    monthlyFee: 4500,
    discount: 0,
    status: 'withdrawn',
    schoolId: SCHOOL_ID,
  },
];

export const MOCK_STAFF: Staff[] = [
  {
    id: 'sf-1',
    name: 'Usman Malik',
    phone: '0300-1112233',
    designation: 'Senior Teacher',
    role: 'teacher',
    joiningDate: '2022-08-15',
    salary: 65000,
    status: 'active',
    schoolId: SCHOOL_ID,
    email: 'teacher@greenvalley.edu.pk',
  },
  {
    id: 'sf-2',
    name: 'Sana Khan',
    phone: '0321-4455667',
    designation: 'School Admin',
    role: 'admin',
    joiningDate: '2021-03-01',
    salary: 75000,
    status: 'active',
    schoolId: SCHOOL_ID,
    email: 'admin@greenvalley.edu.pk',
  },
  {
    id: 'sf-3',
    name: 'Hassan Raza',
    phone: '0333-7788990',
    designation: 'Science Teacher',
    role: 'teacher',
    joiningDate: '2023-01-10',
    salary: 55000,
    status: 'active',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'sf-4',
    name: 'Ayesha Malik',
    phone: '0345-9988776',
    designation: 'English Teacher',
    role: 'teacher',
    joiningDate: '2023-09-01',
    salary: 50000,
    status: 'active',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'sf-5',
    name: 'Bilal Ahmed',
    phone: '0301-3344556',
    designation: 'Math Teacher',
    role: 'teacher',
    joiningDate: '2024-02-20',
    salary: 52000,
    status: 'inactive',
    schoolId: SCHOOL_ID,
  },
];

export const MOCK_FEES: FeeRecord[] = [
  {
    id: 'fee-1',
    studentId: 'st-1',
    studentName: 'Ahmed Ali',
    studentCode: 'ADM-2026-0001',
    className: 'Class 8-A',
    month: 'August 2026',
    totalAmount: 7500,
    paidAmount: 7500,
    remainingAmount: 0,
    status: 'paid',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'fee-2',
    studentId: 'st-2',
    studentName: 'Fatima Khan',
    studentCode: 'ADM-2026-0002',
    className: 'Class 7-A',
    month: 'August 2026',
    totalAmount: 6500,
    paidAmount: 3000,
    remainingAmount: 3500,
    status: 'partial',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'fee-3',
    studentId: 'st-3',
    studentName: 'Hassan Raza',
    studentCode: 'ADM-2026-0003',
    className: 'Class 9-A',
    month: 'August 2026',
    totalAmount: 8000,
    paidAmount: 0,
    remainingAmount: 8000,
    status: 'unpaid',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'fee-4',
    studentId: 'st-4',
    studentName: 'Ayesha Malik',
    studentCode: 'ADM-2026-0004',
    className: 'Class 6-B',
    month: 'August 2026',
    totalAmount: 5000,
    paidAmount: 5000,
    remainingAmount: 0,
    status: 'paid',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'fee-5',
    studentId: 'st-5',
    studentName: 'Bilal Ahmed',
    studentCode: 'ADM-2026-0005',
    className: 'Class 10-A',
    month: 'August 2026',
    totalAmount: 10500,
    paidAmount: 0,
    remainingAmount: 10500,
    status: 'unpaid',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'fee-6',
    studentId: 'st-6',
    studentName: 'Zainab Hussain',
    studentCode: 'ADM-2026-0006',
    className: 'Class 8-B',
    month: 'August 2026',
    totalAmount: 7500,
    paidAmount: 4000,
    remainingAmount: 3500,
    status: 'partial',
    schoolId: SCHOOL_ID,
  },
  {
    id: 'fee-7',
    studentId: 'st-8',
    studentName: 'Maryam Siddiqui',
    studentCode: 'ADM-2026-0008',
    className: 'Class 9-B',
    month: 'July 2026',
    totalAmount: 8500,
    paidAmount: 8500,
    remainingAmount: 0,
    status: 'paid',
    schoolId: SCHOOL_ID,
  },
];

export const MOCK_RECEIPTS: Receipt[] = [
  {
    receiptNumber: '#REC-000421',
    studentName: 'Ahmed Ali',
    studentId: 'ADM-2026-0001',
    className: 'Class 8',
    sectionName: 'A',
    feeMonth: 'August 2026',
    amount: 7500,
    paymentMethod: 'cash',
    date: '2026-08-12',
    receivedBy: 'Sana Khan',
    schoolName: 'Green Valley Academy',
    schoolLogo: null,
  },
  {
    receiptNumber: '#REC-000420',
    studentName: 'Fatima Khan',
    studentId: 'ADM-2026-0002',
    className: 'Class 7',
    sectionName: 'A',
    feeMonth: 'August 2026',
    amount: 3000,
    paymentMethod: 'bank',
    date: '2026-08-10',
    receivedBy: 'Sana Khan',
    schoolName: 'Green Valley Academy',
    schoolLogo: null,
  },
  {
    receiptNumber: '#REC-000419',
    studentName: 'Ayesha Malik',
    studentId: 'ADM-2026-0004',
    className: 'Class 6',
    sectionName: 'B',
    feeMonth: 'August 2026',
    amount: 5000,
    paymentMethod: 'cash',
    date: '2026-08-08',
    receivedBy: 'Imran Qureshi',
    schoolName: 'Green Valley Academy',
    schoolLogo: null,
  },
  {
    receiptNumber: '#REC-000418',
    studentName: 'Maryam Siddiqui',
    studentId: 'ADM-2026-0008',
    className: 'Class 9',
    sectionName: 'B',
    feeMonth: 'July 2026',
    amount: 8500,
    paymentMethod: 'other',
    date: '2026-07-28',
    receivedBy: 'Sana Khan',
    schoolName: 'Green Valley Academy',
    schoolLogo: null,
  },
];

export const MOCK_PAYROLL: PayrollRecord[] = [
  {
    id: 'pr-1',
    staffId: 'sf-1',
    staffName: 'Usman Malik',
    basicSalary: 65000,
    salaryMonth: 'August 2026',
    paidAmount: 65000,
    paymentDate: '2026-08-28',
    status: 'paid',
    role: 'teacher',
  },
  {
    id: 'pr-2',
    staffId: 'sf-2',
    staffName: 'Sana Khan',
    basicSalary: 75000,
    salaryMonth: 'August 2026',
    paidAmount: 75000,
    paymentDate: '2026-08-28',
    status: 'paid',
    role: 'admin',
  },
  {
    id: 'pr-3',
    staffId: 'sf-3',
    staffName: 'Hassan Raza',
    basicSalary: 55000,
    salaryMonth: 'August 2026',
    paidAmount: 0,
    paymentDate: null,
    status: 'unpaid',
    role: 'teacher',
  },
  {
    id: 'pr-4',
    staffId: 'sf-4',
    staffName: 'Ayesha Malik',
    basicSalary: 50000,
    salaryMonth: 'August 2026',
    paidAmount: 0,
    paymentDate: null,
    status: 'unpaid',
    role: 'teacher',
  },
];

export const MOCK_EXPENSES = [
  {
    id: 'ex-1',
    title: 'August Staff Salaries',
    category: 'Salary' as const,
    amount: 297000,
    date: '2026-08-28',
    description: 'Monthly payroll for all active staff',
  },
  {
    id: 'ex-2',
    title: 'Campus Rent',
    category: 'Rent' as const,
    amount: 150000,
    date: '2026-08-01',
    description: 'Monthly campus lease payment',
  },
  {
    id: 'ex-3',
    title: 'LESCO Bill',
    category: 'Electricity' as const,
    amount: 12000,
    date: '2026-08-15',
    description: 'Electricity charges for July–August',
  },
  {
    id: 'ex-4',
    title: 'Exam Stationery',
    category: 'Stationery' as const,
    amount: 8500,
    date: '2026-08-20',
    description: 'Answer sheets and printing supplies',
  },
  {
    id: 'ex-5',
    title: 'AC Repair',
    category: 'Maintenance' as const,
    amount: 15000,
    date: '2026-08-18',
    description: 'Classroom AC servicing',
  },
];

export const MOCK_DASHBOARD = {
  totalStudents: 642,
  presentToday: 587,
  absentToday: 55,
  totalStaff: 28,
  todayFeeCollection: 45000,
  monthFeeCollection: 2450000,
  outstandingFees: 580000,
};

export const MOCK_FEE_CHART = [
  { month: 'Mar', amount: 2100000 },
  { month: 'Apr', amount: 2250000 },
  { month: 'May', amount: 2180000 },
  { month: 'Jun', amount: 1950000 },
  { month: 'Jul', amount: 2320000 },
  { month: 'Aug', amount: 2450000 },
];

export const MOCK_STUDENTS_BY_CLASS = [
  { className: 'Class 6', count: 120 },
  { className: 'Class 7', count: 135 },
  { className: 'Class 8', count: 142 },
  { className: 'Class 9', count: 128 },
  { className: 'Class 10', count: 117 },
];

export const MOCK_ACTIVITY = [
  {
    id: 'act-1',
    type: 'admission' as const,
    description: 'Ahmed Ali admitted — Class 8-A',
    time: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-2',
    type: 'fee' as const,
    description: 'Fee collected from Fatima Khan — Rs. 6,500',
    time: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-3',
    type: 'attendance' as const,
    description: 'Attendance marked for Class 7-B',
    time: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-4',
    type: 'staff' as const,
    description: 'Teacher Usman Malik added',
    time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-5',
    type: 'expense' as const,
    description: 'Electricity expense recorded — Rs. 12,000',
    time: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-6',
    type: 'fee' as const,
    description: 'Partial fee from Zainab Hussain — Rs. 4,000',
    time: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-7',
    type: 'admission' as const,
    description: 'Ayesha Malik admitted — Class 6-B',
    time: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-8',
    type: 'attendance' as const,
    description: 'Attendance marked for Class 10-A',
    time: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_SCHOOLS: School[] = [
  {
    id: SCHOOL_ID,
    name: 'Green Valley Academy',
    logo: null,
    address: '123 Main Road, Gulberg, Lahore',
    phone: '042-35789012',
    email: 'info@greenvalley.edu.pk',
    website: 'https://greenvalley.edu.pk',
    plan: 'professional',
    status: 'active',
    planStartDate: '2026-01-01',
    planRenewalDate: '2027-01-01',
    totalStudents: 642,
    totalStaff: 28,
    ownerEmail: 'owner@greenvalley.edu.pk',
    ownerName: 'Imran Qureshi',
    registeredDate: '2025-11-15',
  },
  {
    id: 'sch-2',
    name: 'Al-Noor Public School',
    logo: null,
    address: 'Block 5, Clifton, Karachi',
    phone: '021-34567890',
    email: 'contact@alnoor.edu.pk',
    website: 'https://alnoor.edu.pk',
    plan: 'premium',
    status: 'active',
    planStartDate: '2025-06-01',
    planRenewalDate: '2026-06-01',
    totalStudents: 1240,
    totalStaff: 52,
    ownerEmail: 'owner@alnoor.edu.pk',
    ownerName: 'Farhan Siddiqui',
    registeredDate: '2025-05-20',
  },
  {
    id: 'sch-3',
    name: 'Beacon Light Academy',
    logo: null,
    address: 'F-8 Markaz, Islamabad',
    phone: '051-2345678',
    email: 'admin@beaconlight.edu.pk',
    website: '',
    plan: 'basic',
    status: 'trial',
    planStartDate: '2026-08-01',
    planRenewalDate: '2026-09-01',
    totalStudents: 180,
    totalStaff: 12,
    ownerEmail: 'owner@beaconlight.edu.pk',
    ownerName: 'Nadia Rehman',
    registeredDate: '2026-08-01',
  },
  {
    id: 'sch-4',
    name: 'Iqra Grammar School',
    logo: null,
    address: 'Satellite Town, Rawalpindi',
    phone: '051-5566778',
    email: 'info@iqragrammar.edu.pk',
    website: '',
    plan: 'professional',
    status: 'active',
    planStartDate: '2025-09-01',
    planRenewalDate: '2026-09-01',
    totalStudents: 890,
    totalStaff: 35,
    ownerEmail: 'owner@iqragrammar.edu.pk',
    ownerName: 'Kamran Aziz',
    registeredDate: '2025-08-12',
  },
  {
    id: 'sch-5',
    name: 'City Model School',
    logo: null,
    address: 'Saddar, Peshawar',
    phone: '091-2233445',
    email: 'office@citymodel.edu.pk',
    website: '',
    plan: 'basic',
    status: 'inactive',
    planStartDate: '2025-03-01',
    planRenewalDate: '2026-03-01',
    totalStudents: 95,
    totalStaff: 8,
    ownerEmail: 'owner@citymodel.edu.pk',
    ownerName: 'Waqas Khan',
    registeredDate: '2025-02-28',
  },
];

export const MOCK_EXAMS: Exam[] = [
  {
    id: 'exm-1',
    title: 'Mid Term Exam 2026',
    examType: 'mid_term',
    classId: 'c8',
    className: 'Class 8',
    sectionId: 's8a',
    sectionName: 'A',
    date: '2026-09-15',
    subjects: [
      { id: 'sub-1', name: 'English', maxMarks: 100 },
      { id: 'sub-2', name: 'Math', maxMarks: 100 },
      { id: 'sub-3', name: 'Physics', maxMarks: 100 },
      { id: 'sub-4', name: 'Urdu', maxMarks: 100 },
    ],
    status: 'completed',
    schoolId: SCHOOL_ID,
    sessionId: 'sess-2627',
  },
  {
    id: 'exm-2',
    title: 'Monthly Test — July',
    examType: 'monthly',
    classId: 'c8',
    className: 'Class 8',
    sectionId: 's8a',
    sectionName: 'A',
    date: '2026-07-28',
    subjects: [
      { id: 'sub-11', name: 'English', maxMarks: 50 },
      { id: 'sub-12', name: 'Math', maxMarks: 50 },
      { id: 'sub-13', name: 'Science', maxMarks: 50 },
    ],
    status: 'completed',
    schoolId: SCHOOL_ID,
    sessionId: 'sess-2627',
  },
  {
    id: 'exm-3',
    title: 'Bi-Monthly Assessment — May/Jun',
    examType: 'bi_monthly',
    classId: 'c8',
    className: 'Class 8',
    sectionId: 's8a',
    sectionName: 'A',
    date: '2026-06-20',
    subjects: [
      { id: 'sub-14', name: 'English', maxMarks: 75 },
      { id: 'sub-15', name: 'Math', maxMarks: 75 },
      { id: 'sub-16', name: 'Urdu', maxMarks: 75 },
    ],
    status: 'completed',
    schoolId: SCHOOL_ID,
    sessionId: 'sess-2627',
  },
  {
    id: 'exm-4',
    title: 'Mock Exam — Board Prep',
    examType: 'mock',
    classId: 'c10',
    className: 'Class 10',
    sectionId: 's10a',
    sectionName: 'A',
    date: '2026-08-10',
    subjects: [
      { id: 'sub-17', name: 'English', maxMarks: 100 },
      { id: 'sub-18', name: 'Math', maxMarks: 100 },
      { id: 'sub-19', name: 'Physics', maxMarks: 100 },
      { id: 'sub-20', name: 'Chemistry', maxMarks: 100 },
    ],
    status: 'completed',
    schoolId: SCHOOL_ID,
    sessionId: 'sess-2627',
  },
  {
    id: 'exm-5',
    title: 'Class Test — Chapter 3',
    examType: 'class_test',
    classId: 'c7',
    className: 'Class 7',
    sectionId: 's7a',
    sectionName: 'A',
    date: '2026-08-18',
    subjects: [
      { id: 'sub-21', name: 'Math', maxMarks: 25 },
      { id: 'sub-22', name: 'Science', maxMarks: 25 },
    ],
    status: 'completed',
    schoolId: SCHOOL_ID,
    sessionId: 'sess-2627',
  },
  {
    id: 'exm-6',
    title: 'Monthly Test — August',
    examType: 'monthly',
    classId: 'c9',
    className: 'Class 9',
    sectionId: 's9a',
    sectionName: 'A',
    date: '2026-08-25',
    subjects: [
      { id: 'sub-8', name: 'English', maxMarks: 75 },
      { id: 'sub-9', name: 'Math', maxMarks: 75 },
      { id: 'sub-10', name: 'Chemistry', maxMarks: 75 },
    ],
    status: 'draft',
    schoolId: SCHOOL_ID,
    sessionId: 'sess-2627',
  },
];

export const MOCK_RESULTS: ExamResult[] = [
  {
    id: 'res-1',
    examId: 'exm-1',
    studentId: 'st-1',
    studentName: 'Ahmed Ali',
    marks: { 'sub-1': 78, 'sub-2': 85, 'sub-3': 72, 'sub-4': 80 },
    total: 400,
    obtained: 315,
    percentage: 79,
    grade: 'B+',
    deliveryStatus: 'sent',
    lastSentAt: '2026-09-16T11:20:00',
  },
  {
    id: 'res-2',
    examId: 'exm-1',
    studentId: 'st-6',
    studentName: 'Zainab Hussain',
    marks: { 'sub-1': 88, 'sub-2': 92, 'sub-3': 81, 'sub-4': 85 },
    total: 400,
    obtained: 346,
    percentage: 87,
    grade: 'A',
    deliveryStatus: 'not_sent',
    lastSentAt: null,
  },
  {
    id: 'res-3',
    examId: 'exm-2',
    studentId: 'st-1',
    studentName: 'Ahmed Ali',
    marks: { 'sub-11': 42, 'sub-12': 45, 'sub-13': 38 },
    total: 150,
    obtained: 125,
    percentage: 83,
    grade: 'A',
    deliveryStatus: 'sent',
    lastSentAt: '2026-07-29T09:15:00',
  },
  {
    id: 'res-4',
    examId: 'exm-3',
    studentId: 'st-1',
    studentName: 'Ahmed Ali',
    marks: { 'sub-14': 60, 'sub-15': 68, 'sub-16': 55 },
    total: 225,
    obtained: 183,
    percentage: 81,
    grade: 'A',
    deliveryStatus: 'sent',
    lastSentAt: '2026-06-21T16:00:00',
  },
  {
    id: 'res-5',
    examId: 'exm-2',
    studentId: 'st-6',
    studentName: 'Zainab Hussain',
    marks: { 'sub-11': 48, 'sub-12': 46, 'sub-13': 44 },
    total: 150,
    obtained: 138,
    percentage: 92,
    grade: 'A+',
    deliveryStatus: 'failed',
    lastSentAt: '2026-07-29T09:18:00',
  },
  {
    id: 'res-6',
    examId: 'exm-4',
    studentId: 'st-5',
    studentName: 'Bilal Ahmed',
    marks: { 'sub-17': 72, 'sub-18': 81, 'sub-19': 68, 'sub-20': 75 },
    total: 400,
    obtained: 296,
    percentage: 74,
    grade: 'B+',
    deliveryStatus: 'not_sent',
    lastSentAt: null,
  },
  {
    id: 'res-7',
    examId: 'exm-5',
    studentId: 'st-2',
    studentName: 'Fatima Khan',
    marks: { 'sub-21': 22, 'sub-22': 20 },
    total: 50,
    obtained: 42,
    percentage: 84,
    grade: 'A',
    deliveryStatus: 'sent',
    lastSentAt: '2026-08-18T14:30:00',
  },
];

export const MOCK_RESULT_DELIVERIES: ResultDeliveryRecord[] = [
  {
    id: 'rd-1',
    resultId: 'res-1',
    examId: 'exm-1',
    examTitle: 'Mid Term Exam 2026',
    examType: 'mid_term',
    studentId: 'st-1',
    studentName: 'Ahmed Ali',
    guardianName: 'Khalid Ali',
    phone: '0300-1234567',
    message:
      "Dear Parent, Ahmed Ali's result for Mid Term Exam 2026 (Mid Term) — Class 8-A. Total: 315/400 (79%, Grade B+). — Green Valley Academy",
    status: 'Sent',
    sentAt: '2026-09-16T11:20:00',
    sentBy: 'Sana Khan',
  },
  {
    id: 'rd-2',
    resultId: 'res-3',
    examId: 'exm-2',
    examTitle: 'Monthly Test — July',
    examType: 'monthly',
    studentId: 'st-1',
    studentName: 'Ahmed Ali',
    guardianName: 'Khalid Ali',
    phone: '0300-1234567',
    message:
      "Dear Parent, Ahmed Ali's result for Monthly Test — July (Monthly Test). Total: 125/150 (83%, Grade A). — Green Valley Academy",
    status: 'Sent',
    sentAt: '2026-07-29T09:15:00',
    sentBy: 'Sana Khan',
  },
  {
    id: 'rd-3',
    resultId: 'res-4',
    examId: 'exm-3',
    examTitle: 'Bi-Monthly Assessment — May/Jun',
    examType: 'bi_monthly',
    studentId: 'st-1',
    studentName: 'Ahmed Ali',
    guardianName: 'Khalid Ali',
    phone: '0300-1234567',
    message:
      "Dear Parent, Ahmed Ali's result for Bi-Monthly Assessment — May/Jun. Total: 183/225 (81%, Grade A). — Green Valley Academy",
    status: 'Sent',
    sentAt: '2026-06-21T16:00:00',
    sentBy: 'Usman Malik',
  },
  {
    id: 'rd-4',
    resultId: 'res-5',
    examId: 'exm-2',
    examTitle: 'Monthly Test — July',
    examType: 'monthly',
    studentId: 'st-6',
    studentName: 'Zainab Hussain',
    guardianName: 'Ali Hussain',
    phone: '0312-9988776',
    message:
      "Dear Parent, Zainab Hussain's result for Monthly Test — July. Total: 138/150 (92%, Grade A+). — Green Valley Academy",
    status: 'Failed',
    sentAt: '2026-07-29T09:18:00',
    sentBy: 'Sana Khan',
  },
  {
    id: 'rd-5',
    resultId: 'res-7',
    examId: 'exm-5',
    examTitle: 'Class Test — Chapter 3',
    examType: 'class_test',
    studentId: 'st-2',
    studentName: 'Fatima Khan',
    guardianName: 'Tariq Khan',
    phone: '0321-9876543',
    message:
      "Dear Parent, Fatima Khan's result for Class Test — Chapter 3. Total: 42/50 (84%, Grade A). — Green Valley Academy",
    status: 'Sent',
    sentAt: '2026-08-18T14:30:00',
    sentBy: 'Sana Khan',
  },
];

export const MOCK_NOTIFICATION_HISTORY = [
  {
    id: 'n-1',
    recipient: 'Khalid Ali',
    phone: '0300-1234567',
    type: 'Fee Reminder',
    status: 'Sent' as const,
    date: '2026-08-28T10:30:00',
  },
  {
    id: 'n-2',
    recipient: 'Tariq Khan',
    phone: '0321-9876543',
    type: 'Payment Confirmation',
    status: 'Sent' as const,
    date: '2026-08-27T14:15:00',
  },
  {
    id: 'n-3',
    recipient: 'Javed Raza',
    phone: '0333-4567890',
    type: 'Absence Alert',
    status: 'Failed' as const,
    date: '2026-08-26T09:00:00',
  },
];

export const MOCK_SAAS_METRICS = {
  totalSchools: 12,
  activeSchools: 9,
  trialSchools: 2,
  inactiveSchools: 1,
  totalStudents: 8420,
  totalStaff: 312,
  mrr: 485000,
};

export const MOCK_SCHOOLS_BY_PLAN = [
  { name: 'Basic', value: 4 },
  { name: 'Professional', value: 5 },
  { name: 'Premium', value: 3 },
];

export const MOCK_SCHOOLS_BY_MONTH = [
  { month: 'Mar', count: 1 },
  { month: 'Apr', count: 2 },
  { month: 'May', count: 1 },
  { month: 'Jun', count: 3 },
  { month: 'Jul', count: 2 },
  { month: 'Aug', count: 3 },
];

export const MOCK_ATTENDANCE_TREND = Array.from({ length: 30 }, (_, i) => ({
  day: String(i + 1),
  percentage: 85 + Math.round(Math.sin(i / 3) * 8 + (i % 5)),
}));

export const MOCK_EXPENSE_CHART = [
  { month: 'Mar', amount: 420000 },
  { month: 'Apr', amount: 445000 },
  { month: 'May', amount: 410000 },
  { month: 'Jun', amount: 480000 },
  { month: 'Jul', amount: 455000 },
  { month: 'Aug', amount: 482500 },
];

export const MOCK_EXPENSE_BY_CATEGORY = [
  { name: 'Salary', value: 297000 },
  { name: 'Rent', value: 150000 },
  { name: 'Electricity', value: 12000 },
  { name: 'Stationery', value: 8500 },
  { name: 'Maintenance', value: 15000 },
];

export const GUARDIANS: Record<string, { name: string; phone: string; cnic: string; address: string }> = {
  'st-1': {
    name: 'Khalid Ali',
    phone: '0300-1234567',
    cnic: '35202-1234567-1',
    address: 'House 42, Gulberg III, Lahore',
  },
  'st-2': {
    name: 'Tariq Khan',
    phone: '0321-9876543',
    cnic: '35202-7654321-2',
    address: 'Street 7, Model Town, Lahore',
  },
};
